### ISSUE TITLE
Questions regarding @objc usage + Multiplatform Swift support. 

### ISSUE THREAD

**Issue by ghost** [wxxsw/SwiftTheme#162]
Why does this library reference `@objc` so much? 

Also, does it support `tvOS`, `macOS`, and `watchOS`? 🤔

**Comment by wxxsw** [comment]
Because this library also supports objective-c.

SwiftTheme only supports iOS9+ and tvOS9+

**Comment by sammycooks999** [comment]
What do you think it would take to accomplish a goal of `macOS and tvOS? `

**Comment by sammycooks999** [comment]
Maybe this can help us? @wxxsw  - https://github.com/devicekit/DeviceKit

**Comment by wxxsw** [comment]
The main work is that each time a platform is added, we need to extend the theme_ method for each ui component of the corresponding platform. Because tvOS is the same as the iOS control, it is compatible.

All my repositories are what I used to use and my main job is to develop for iOS, so I can guarantee that it will work on iOS. For example to support macOS, I may not be able to guarantee its stability, so I will not do that.

**Comment by sammycooks999** [comment]
Are you will to accept contributions from the community? @wxxsw

**Comment by wxxsw** [comment]
Generally I will accept small submissions. If it is a large submission, there will be higher requirements. For example, if you want to support macOS, there is a simple Demo, and you need to consider that it will not affect the work of iOS and tvOS. This may require a lot of judgment on the existing library, because many iOS, The common controls of tvOS have not been judged by the device, and the final code quality will not deteriorate.
