### ISSUE TITLE
tvOS support?

### ISSUE THREAD

**Issue by miqdadz** [wxxsw/SwiftTheme#42]
any plan to support tvOS?

**Comment by wxxsw** [comment]
Now has been initially compatible with the tvOS, because I do not know very much about tvOS, currently only support the existence of iOS controls. In the future I will add support for all tvOS controls, and provide tvOS demo.

Install:
```ruby
pod 'SwiftTheme', :git => 'https://github.com/jiecao-fm/SwiftTheme.git'
```

If there is a follow-up update, I will continue to reply here.
