### ISSUE TITLE
Cannot invoke initializer for type 'UIView' with no arguments

### ISSUE THREAD

**Issue by zenghaojim33** [wxxsw/SwiftTheme#84]
After importing this library I can not use UIView() or UIView subclass initilizer without argument. Any idea why and how to solve this?

**Comment by kcramer** [comment]
I don't see any issue using UIView().  Are you using the most recent version of the library?

**Comment by Mackis** [comment]
> I think there it's due to conflicts with other libraries and I'm still looking into it.
> Also this problem may be related to #83
> I am using [TagListView](https://github.com/ElaWorkshop/TagListView/issues) and when I am using SwiftTheme as pod and TagListView as source files, the build failed.
> There is no problem when using both as pod or source files.
> 
> [2313123.zip](https://github.com/jiecao-fm/SwiftTheme/files/2467522/2313123.zip)

I was also experiencing this problem. After reading @zenghaojim33 response on this issue I resolved the problem by removing SwiftTheme from my podFile and added the source files directly to my project and was able to build succesfully on Xcode10.

**Comment by kcramer** [comment]
I assume everyone having this issue is getting the latest 0.4.2 Cocopod and is not getting it directly from GitHub?

It appears the Cocoapod that is downloaded does not contain my fix.

Try replacing this line in the pod:

```
    pod 'SwiftTheme', '~> 0.4.2'
```

with this line:

```
    pod 'SwiftTheme', :git => 'git@github.com:jiecao-fm/SwiftTheme.git'
```

I think @wxxsw needs to push another release on GitHub and the Cocoapod. It appears the 0.4.2 release on GitHub and hence the Cocoapod do not contain my fix.  It is present in the latest code on GItHub though.

**Comment by kcramer** [comment]
Version 0.4.3 should fix these issues.  You will need to `pod update SwiftTheme` to get the new version.  Let me know if that fixes your issues.
