### ISSUE TITLE
Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by wty302857194** [wxxsw/SwiftTheme#93]
<img width="567" alt="image" src="https://user-images.githubusercontent.com/12996539/55403818-3a63a480-5589-11e9-8083-8c98c1a92407.png">

**Comment by kcramer** [comment]
You will need to provide more information for help.  It looks likely that there is an issue setting up the theme on the object.  Can you provide the relevant code fragment where you assign a theme to the object?

**Comment by wty302857194** [comment]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/12996539/55461227-81ec3e00-5626-11e9-99ee-9d212d0a4657.png">
<img width="648" alt="image" src="https://user-images.githubusercontent.com/12996539/55461402-edcea680-5626-11e9-8076-fb08aa7d134c.png">

**Comment by wxxsw** [comment]
Thanks for the feedback, I think the reason may be that the value corresponding to keyPath does not exist, or the value is in the wrong format.

But SwiftTheme shouldn’t crash, I will fix this.

**Comment by kcramer** [comment]
As @wxxsw said, you must have a typo between the names in the Plist file and the names used in your code.  This error is probably caused by a mismatch on one of the buttons.  I would also check the console to see if you see any error messages about missing values.

I created a PR #94 that will prevent the crash and print a warning message.
